name = "WorldBankData"
uuid = "2ff30676-a39f-58b2-ad74-5d1012d57b9b"
version = "0.3.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
DataFrames = "^0.20, 0.21"
HTTP = "^0.8"
JSON = "^0.21"
julia = "^1.3"
