name = "WorldBankData"
uuid = "2ff30676-a39f-58b2-ad74-5d1012d57b9b"
version = "0.4.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
DataFrames = "^0.21"
HTTP = "^0.9"
JSON = "^0.21"
julia = "^1.5"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DocumentFormat = "ffa9a821-9c82-50df-894e-fbcef3ed31cd"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "CSV", "DocumentFormat", "FilePathsBase"]
